
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "@/component/LogoutBtn";
import WindowOpen from "@/component/WindowOpen";
import AlertPG from "@/component/AlertPG";
import AlertSe from "@/component/AlertSe";
import NavbarList from "@/component/NavbarList";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let adminStatus = await getServerSession(authOptions)
  console.log(adminStatus)
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* 모든 페이지에 보일 HTML은 layouy.js에 작성 */}
        <header className="navbar">
          <div className="navbar-logo">
            <Link href="/">Walker's Devlog</Link>
          </div>
          <div className="navbar-main">
            
            <button className="navbar-main-aboutme"
              style={{
                display: adminStatus?.user?.name === "Suyoung Jung" ? "block" : "none",
              }}
            >관리자요
            </button>
            <span>
              <button className="navbar-main-playground"
                style={{
                  display: adminStatus?.user?.name === "Suyoung Jung" ? "block" : "none",
                }}
                ><LogoutBtn/>
                </button>
            </span>
            <button className="navbar-main-aboutme">
              <WindowOpen></WindowOpen>
              </button>
            <button className="navbar-main-playground">
              <AlertPG></AlertPG>
            </button>
            {/* 추후 고도화 과정에서 추가 예정 */}
            <div className="navbar-main-search" style={{display: "none"}}>
              <img src="/searchImg.svg" className="navbar-main-search-img"/>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
